package mekanism.client.model;

import javax.annotation.Nonnull;
import mekanism.client.render.MekanismRenderType;
import mekanism.common.util.MekanismUtils;
import mekanism.common.util.MekanismUtils.ResourceType;
import net.minecraft.client.model.ModelPart;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.VertexConsumer;
import net.minecraft.client.render.VertexConsumerProvider;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.util.Identifier;

public class ModelChemicalDissolutionChamber extends MekanismJavaModel {

    private static final Identifier DISSOLUTION_TEXTURE = MekanismUtils.getResource(ResourceType.RENDER, "chemical_dissolution_chamber.png");
    private final RenderLayer RENDER_TYPE = getLayer(DISSOLUTION_TEXTURE);
    private final RenderLayer GLASS_RENDER_TYPE = MekanismRenderType.mekStandard(DISSOLUTION_TEXTURE);

    private final ModelPart support2;
    private final ModelPart vat5;
    private final ModelPart top2;
    private final ModelPart top;
    private final ModelPart base;
    private final ModelPart vat2;
    private final ModelPart vat3;
    private final ModelPart vat6;
    private final ModelPart vat9;
    private final ModelPart vat8;
    private final ModelPart vat7;
    private final ModelPart vat4;
    private final ModelPart backEdge2;
    private final ModelPart back;
    private final ModelPart backEdge1;
    private final ModelPart vents;
    private final ModelPart support1;
    private final ModelPart vat1;
    private final ModelPart nozzle8;
    private final ModelPart nozzle5;
    private final ModelPart nozzle7;
    private final ModelPart nozzle4;
    private final ModelPart nozzle9;
    private final ModelPart nozzle6;
    private final ModelPart nozzle3;
    private final ModelPart nozzle2;
    private final ModelPart nozzle1;
    private final ModelPart glass;
    private final ModelPart portToggle1;
    private final ModelPart portToggle2;

    public ModelChemicalDissolutionChamber() {
        super(RenderLayer::getEntitySolid);
        textureWidth = 128;
        textureHeight = 64;

        support2 = new ModelPart(this, 4, 0);
        support2.addCuboid(0F, 0F, 0F, 1, 2, 1, false);
        support2.setPivot(6F, 9F, -7F);
        support2.setTextureSize(128, 64);
        support2.mirror = true;
        setRotation(support2, 0F, 0F, 0F);
        vat5 = new ModelPart(this, 0, 23);
        vat5.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat5.setPivot(-1.5F, 13F, -1.5F);
        vat5.setTextureSize(128, 64);
        vat5.mirror = true;
        setRotation(vat5, 0F, 0F, 0F);
        top2 = new ModelPart(this, 0, 40);
        top2.addCuboid(0F, 0F, 0F, 16, 1, 15, false);
        top2.setPivot(-8F, 11F, -8F);
        top2.setTextureSize(128, 64);
        top2.mirror = true;
        setRotation(top2, 0F, 0F, 0F);
        top = new ModelPart(this, 0, 23);
        top.addCuboid(0F, 0F, 0F, 16, 1, 16, false);
        top.setPivot(-8F, 8F, -8F);
        top.setTextureSize(128, 64);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
        base = new ModelPart(this, 0, 0);
        base.addCuboid(0F, 0F, 0F, 16, 7, 16, false);
        base.setPivot(-8F, 17F, -8F);
        base.setTextureSize(128, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        vat2 = new ModelPart(this, 0, 23);
        vat2.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat2.setPivot(-5F, 13F, -1.5F);
        vat2.setTextureSize(128, 64);
        vat2.mirror = true;
        setRotation(vat2, 0F, 0F, 0F);
        vat3 = new ModelPart(this, 0, 23);
        vat3.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat3.setPivot(-5F, 13F, 2F);
        vat3.setTextureSize(128, 64);
        vat3.mirror = true;
        setRotation(vat3, 0F, 0F, 0F);
        vat6 = new ModelPart(this, 0, 23);
        vat6.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat6.setPivot(-1.5F, 13F, 2F);
        vat6.setTextureSize(128, 64);
        vat6.mirror = true;
        setRotation(vat6, 0F, 0F, 0F);
        vat9 = new ModelPart(this, 0, 23);
        vat9.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat9.setPivot(2F, 13F, 2F);
        vat9.setTextureSize(128, 64);
        vat9.mirror = true;
        setRotation(vat9, 0F, 0F, 0F);
        vat8 = new ModelPart(this, 0, 23);
        vat8.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat8.setPivot(2F, 13F, -1.5F);
        vat8.setTextureSize(128, 64);
        vat8.mirror = true;
        setRotation(vat8, 0F, 0F, 0F);
        vat7 = new ModelPart(this, 0, 23);
        vat7.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat7.setPivot(2F, 13F, -5F);
        vat7.setTextureSize(128, 64);
        vat7.mirror = true;
        setRotation(vat7, 0F, 0F, 0F);
        vat4 = new ModelPart(this, 0, 23);
        vat4.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat4.setPivot(-1.5F, 13F, -5F);
        vat4.setTextureSize(128, 64);
        vat4.mirror = true;
        setRotation(vat4, 0F, 0F, 0F);
        backEdge2 = new ModelPart(this, 8, 0);
        backEdge2.addCuboid(0F, 0F, 0F, 1, 8, 1, false);
        backEdge2.setPivot(7F, 9F, 7F);
        backEdge2.setTextureSize(128, 64);
        backEdge2.mirror = true;
        setRotation(backEdge2, 0F, 0F, 0F);
        back = new ModelPart(this, 48, 0);
        back.addCuboid(0F, 0F, 0F, 14, 8, 2, false);
        back.setPivot(-7F, 9F, 6F);
        back.setTextureSize(128, 64);
        back.mirror = true;
        setRotation(back, 0F, 0F, 0F);
        backEdge1 = new ModelPart(this, 8, 0);
        backEdge1.addCuboid(0F, 0F, 0F, 1, 8, 1, false);
        backEdge1.setPivot(-8F, 9F, 7F);
        backEdge1.setTextureSize(128, 64);
        backEdge1.mirror = true;
        setRotation(backEdge1, 0F, 0F, 0F);
        vents = new ModelPart(this, 70, 0);
        vents.addCuboid(0F, 0F, 0F, 8, 2, 10, false);
        vents.setPivot(-4F, 9F, -4F);
        vents.setTextureSize(128, 64);
        vents.mirror = true;
        setRotation(vents, 0F, 0F, 0F);
        support1 = new ModelPart(this, 4, 0);
        support1.addCuboid(0F, 0F, 0F, 1, 2, 1, false);
        support1.setPivot(-7F, 9F, -7F);
        support1.setTextureSize(128, 64);
        support1.mirror = true;
        setRotation(support1, 0F, 0F, 0F);
        vat1 = new ModelPart(this, 0, 23);
        vat1.addCuboid(0F, 0F, 0F, 3, 4, 3, false);
        vat1.setPivot(-5F, 13F, -5F);
        vat1.setTextureSize(128, 64);
        vat1.mirror = true;
        setRotation(vat1, 0F, 0F, 0F);
        nozzle8 = new ModelPart(this, 0, 0);
        nozzle8.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle8.setPivot(3F, 11.5F, -0.5F);
        nozzle8.setTextureSize(128, 64);
        nozzle8.mirror = true;
        setRotation(nozzle8, 0F, 0F, 0F);
        nozzle5 = new ModelPart(this, 0, 0);
        nozzle5.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle5.setPivot(-0.5F, 11.5F, -0.5F);
        nozzle5.setTextureSize(128, 64);
        nozzle5.mirror = true;
        setRotation(nozzle5, 0F, 0F, 0F);
        nozzle7 = new ModelPart(this, 0, 0);
        nozzle7.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle7.setPivot(3F, 11.5F, -4F);
        nozzle7.setTextureSize(128, 64);
        nozzle7.mirror = true;
        setRotation(nozzle7, 0F, 0F, 0F);
        nozzle4 = new ModelPart(this, 0, 0);
        nozzle4.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle4.setPivot(-0.5F, 11.5F, -4F);
        nozzle4.setTextureSize(128, 64);
        nozzle4.mirror = true;
        setRotation(nozzle4, 0F, 0F, 0F);
        nozzle9 = new ModelPart(this, 0, 0);
        nozzle9.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle9.setPivot(3F, 11.5F, 3F);
        nozzle9.setTextureSize(128, 64);
        nozzle9.mirror = true;
        setRotation(nozzle9, 0F, 0F, 0F);
        nozzle6 = new ModelPart(this, 0, 0);
        nozzle6.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle6.setPivot(-0.5F, 11.5F, 3F);
        nozzle6.setTextureSize(128, 64);
        nozzle6.mirror = true;
        setRotation(nozzle6, 0F, 0F, 0F);
        nozzle3 = new ModelPart(this, 0, 0);
        nozzle3.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle3.setPivot(-4F, 11.5F, 3F);
        nozzle3.setTextureSize(128, 64);
        nozzle3.mirror = true;
        setRotation(nozzle3, 0F, 0F, 0F);
        nozzle2 = new ModelPart(this, 0, 0);
        nozzle2.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle2.setPivot(-4F, 11.5F, -0.5F);
        nozzle2.setTextureSize(128, 64);
        nozzle2.mirror = true;
        setRotation(nozzle2, 0F, 0F, 0F);
        nozzle1 = new ModelPart(this, 0, 0);
        nozzle1.addCuboid(0F, 0F, 0F, 1, 1, 1, false);
        nozzle1.setPivot(-4F, 11.5F, -4F);
        nozzle1.setTextureSize(128, 64);
        nozzle1.mirror = true;
        setRotation(nozzle1, 0F, 0F, 0F);
        glass = new ModelPart(this, 64, 14);
        glass.addCuboid(0F, 0F, 0F, 14, 5, 13, false);
        glass.setPivot(-7F, 12F, -7F);
        glass.setTextureSize(128, 64);
        glass.mirror = true;
        setRotation(glass, 0F, 0F, 0F);
        portToggle1 = new ModelPart(this, 106, 0);
        portToggle1.addCuboid(0F, 0F, 0F, 1, 10, 10, false);
        portToggle1.setPivot(-8.01F, 10.99F, -5F);
        portToggle1.setTextureSize(128, 64);
        portToggle1.mirror = true;
        setRotation(portToggle1, 0F, 0F, 0F);
        portToggle2 = new ModelPart(this, 64, 32);
        portToggle2.addCuboid(0F, 0F, 0F, 1, 8, 8, false);
        portToggle2.setPivot(7.01F, 12F, -4F);
        portToggle2.setTextureSize(128, 64);
        portToggle2.mirror = true;
        setRotation(portToggle2, 0F, 0F, 0F);
    }

    public void render(@Nonnull MatrixStack matrix, @Nonnull VertexConsumerProvider renderer, int light, int overlayLight, boolean hasEffect) {
        render(matrix, getVertexBuilder(renderer, RENDER_TYPE, hasEffect), light, overlayLight, 1, 1, 1, 1);
        //Render the glass on a more translucent layer
        //Note: The glass makes water, ice etc behind it invisible. This is due to an engine limitation
        glass.render(matrix, getVertexBuilder(renderer, GLASS_RENDER_TYPE, hasEffect), light, overlayLight, 1, 1, 1, 1);
    }

    @Override
    public void render(@Nonnull MatrixStack matrix, @Nonnull VertexConsumer vertexBuilder, int light, int overlayLight, float red, float green, float blue, float alpha) {
        support2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat5.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        top2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        top.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        base.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat3.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat6.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat9.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat8.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat7.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat4.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        backEdge2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        back.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        backEdge1.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vents.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        support1.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        vat1.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle8.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle5.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle7.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle4.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle9.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle6.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle3.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        nozzle1.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        portToggle1.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
        portToggle2.render(matrix, vertexBuilder, light, overlayLight, red, green, blue, alpha);
    }
}